(define (problem myProblem_phase1)
(:domain myDomain_phase1)
(:objects 
design - Design
boron - BoronMaterial
phosphor - PhosphorMaterial
silicon - SiliconMaterial
aluminum - AluminumMaterial
resist - ResistMaterial
plastic - PlasticMaterial
chemicals - ChemicalsMaterial
copper - CopperMaterial
wafer - Material
true - Boolean
false - Boolean
available - State
broken - State
taking_silicon - Capability
taking_boron - Capability
taking_copper - Capability
taking_design - Capability
taking_phosphor - Capability
taking_resist - Capability
taking_chemicals - Capability
taking_aluminum - Capability
taking_plastic - Capability
taking_wafer - Capability
inventorynorway - Service_inv_no
inventorybolivia - Service_inv_bo
inventoryperu - Service_inv_pe
inventoryrussia - Service_inv_ru
designerusa - Service_des_us
inventorykazakhstan - Service_inv_kz
inventorymalaysia - Service_inv_my
inventoryusa - Service_inv_us
inventoryturkey - Service_inv_tr
inventoryargentina - Service_inv_ar
inventoryaustria - Service_inv_aus
inventoryindia - Service_inv_in
inventoryfrance - Service_inv_fr
inventorysvizzera - Service_inv_sv
designertaiwan - Service_des_tw
designerchina - Service_des_ch
inventorymorocco - Service_inv_ma
designeruk - Service_des_uk
inventorychile - Service_inv_cl
inventoryjapan - Service_inv_jp
inventorycanada - Service_inv_ca
inventorybelgio - Service_inv_be
inventoryaustralia - Service_inv_au
inventorychina - Service_inv_cn
inventorysouthkorea - Service_inv_kr
inventorybrazil - Service_inv_br
)
(:init 
(provides inventorynorway taking_silicon)
(provides inventorybolivia taking_boron)
(provides inventoryperu taking_copper)
(provides inventoryrussia taking_silicon)
(provides inventoryrussia taking_boron)
(provides designerusa taking_design)
(provides inventorykazakhstan taking_boron)
(provides inventorymalaysia taking_silicon)
(provides inventoryusa taking_boron)
(provides inventoryusa taking_phosphor)
(provides inventoryusa taking_silicon)
(provides inventoryusa taking_resist)
(provides inventoryusa taking_chemicals)
(provides inventoryusa taking_copper)
(provides inventoryturkey taking_boron)
(provides inventoryargentina taking_boron)
(provides inventoryaustria taking_resist)
(provides inventoryindia taking_aluminum)
(provides inventoryindia taking_resist)
(provides inventoryindia taking_plastic)
(provides inventoryfrance taking_silicon)
(provides inventorysvizzera taking_resist)
(provides designertaiwan taking_design)
(provides designerchina taking_design)
(provides inventorymorocco taking_phosphor)
(provides designeruk taking_design)
(provides inventorychile taking_boron)
(provides inventorychile taking_copper)
(provides inventoryjapan taking_wafer)
(provides inventorycanada taking_resist)
(provides inventorycanada taking_chemicals)
(provides inventorybelgio taking_resist)
(provides inventoryaustralia taking_aluminum)
(provides inventorychina taking_boron)
(provides inventorychina taking_silicon)
(provides inventorychina taking_phosphor)
(provides inventorychina taking_plastic)
(provides inventorychina taking_copper)
(provides inventorysouthkorea taking_wafer)
(provides inventorybrazil taking_silicon)
(provides inventorybrazil taking_aluminum)
(status inventorynorway available)
(status inventorybolivia available)
(status inventoryperu available)
(status inventoryrussia available)
(status designerusa available)
(status inventorykazakhstan available)
(taken wafer false)
(status inventorymalaysia available)
(status inventoryusa available)
(taken boron false)
(status inventoryturkey available)
(status inventoryargentina available)
(taken design false)
(taken copper false)
(taken plastic false)
(status inventoryaustria available)
(status inventoryindia available)
(status inventoryfrance available)
(status inventorysvizzera available)
(taken resist false)
(status designertaiwan available)
(taken aluminum false)
(taken chemicals false)
(status designerchina available)
(status inventorymorocco available)
(status designeruk available)
(status inventorychile available)
(status inventoryjapan available)
(status inventorycanada available)
(taken phosphor false)
(status inventorybelgio available)
(status inventoryaustralia available)
(status inventorychina available)
(status inventorysouthkorea available)
(status inventorybrazil available)
(taken silicon false)
(= (total-cost) 0)
)
(:goal 
(and 
(taken design true)
(taken boron true)
(taken phosphor true)
(taken silicon true)
(taken aluminum true)
(taken resist true)
(taken plastic true)
(taken chemicals true)
(taken copper true)
(taken design true)
)
)
(:metric minimize (total-cost))

)